language: c
compiler:
- clang
- gcc
before_install:
- sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
install:
- sudo apt-get update -qq
- sudo apt-get install cmake libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev
before_script:
- cd build

script:
- cmake ..
- make
