#ifndef CONFIG_H
#define CONFIG_H

#define BASE_HEIGHT 224
#define BASE_WIDTH 256

#define WINDOW_HEIGHT (BASE_HEIGHT*2)
#define WINDOW_WIDTH (BASE_WIDTH*2)

#define FPS_CAP 60
#define TICKS_PER_FRAME (1000 / FPS_CAP)

#endif /* CONFIG_H */
